use_frameworks!

platform :ios, '10.0'

target 'CustomKit_Example' do
  
  pod 'CustomKit', :path => '../'
  
  pod 'CMCommonModuleMediator', :path => '../'

  target 'CustomKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
